# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ovs_monitor_pb2 as ovs__monitor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ovs_monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OvsMonitorStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMetrics = channel.unary_unary(
                '/ovsmonitor.OvsMonitor/GetMetrics',
                request_serializer=ovs__monitor__pb2.OvsRequest.SerializeToString,
                response_deserializer=ovs__monitor__pb2.OvsResponse.FromString,
                _registered_method=True)
        self.SetSliceLimit = channel.unary_unary(
                '/ovsmonitor.OvsMonitor/SetSliceLimit',
                request_serializer=ovs__monitor__pb2.SetSliceLimitRequest.SerializeToString,
                response_deserializer=ovs__monitor__pb2.SetSliceLimitResponse.FromString,
                _registered_method=True)


class OvsMonitorServicer(object):
    """Service
    """

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSliceLimit(self, request, context):
        """Live limit setting without traffic interruption
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OvsMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=ovs__monitor__pb2.OvsRequest.FromString,
                    response_serializer=ovs__monitor__pb2.OvsResponse.SerializeToString,
            ),
            'SetSliceLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSliceLimit,
                    request_deserializer=ovs__monitor__pb2.SetSliceLimitRequest.FromString,
                    response_serializer=ovs__monitor__pb2.SetSliceLimitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ovsmonitor.OvsMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ovsmonitor.OvsMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OvsMonitor(object):
    """Service
    """

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ovsmonitor.OvsMonitor/GetMetrics',
            ovs__monitor__pb2.OvsRequest.SerializeToString,
            ovs__monitor__pb2.OvsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSliceLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ovsmonitor.OvsMonitor/SetSliceLimit',
            ovs__monitor__pb2.SetSliceLimitRequest.SerializeToString,
            ovs__monitor__pb2.SetSliceLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
